### ISSUE TITLE
Návrh prekladu Chesty Turbo z 190.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#10]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/e32ea624-9646-4ea5-a2eb-853bccb64329)

Kozatka Turbo?

**Comment by PetrCejpek** [comment]
No, mně to spíš přijde jak jméno nějaké pornoherečky. Já bych to asi nechal.
