### ISSUE TITLE
Michelle Milkenová (název speakera)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#100]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/9014ee82-74dc-42f3-8927-03f7cfa86723)

**Michelle Milkenová** (název speakera)

**Comment by miracleflame** [comment]
Opravené v [hromady oprav](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/commit/1aea113267e2e6989b8ce7b29e84c337e9ef23fa) https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/8 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/9 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/12 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/14 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/15
