### ISSUE TITLE
Kazeta s Michelle Milkenovou

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#103]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/33cadd28-d024-4e64-9230-3be13d46a702)

Tady si nejsem jistý, jestli se jedná o chybu - tohle je totiž název předmětu. Jedná se o kazetu, na kterou Larry natočil Michelle Milkenovou.

**Comment by miracleflame** [comment]
Toto vypadá na konflikt uloženej pozície s pozmenenými skriptami. Práve sa mi stalo niečo podobné, ale iné, keď som sa to pokúsil zreplikovať.
Preverím viac a napíšem...

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/3793138b-e01f-4fde-93e2-2a358fbe1933)
Zreplikoval jsem (obdobnou verzi).

**Comment by miracleflame** [comment]
A môžeš povedať s určitosťou, že si nemal menené skripty od začiatku počas celého priebehu?

**Comment by PetrCejpek** [comment]
Včera cca v 18 hodin jsem stáhnul aktuální repozitář, nakopíroval všechno do složky se hrou a udělal průběh, dokud mi nespadla hra (#195). Tenhle poslední screenshot jsem dělal dneska večer - nahrazoval jsem některé tex soubory, ale src určitě ne.

**Comment by miracleflame** [comment]
A nie sú tie texty k nahrávkam svojim spôsobom k veci? Ja som bol zatiaľ iba u Chi Chi
![obrázok](https://github.com/user-attachments/assets/bcbfcc5d-66f9-4026-8847-da2807ca4879)

**Comment by miracleflame** [comment]
Našiel som v Main.sc názvy týchto náhrávok. Prepíšem to na "Nahrávka -ové" či Záznam?

**Comment by PetrCejpek** [comment]
> A nie sú tie texty k nahrávkam svojim spôsobom k veci? Ja som bol zatiaľ iba u Chi Chi ![obrázok](https://private-user-images.githubusercontent.com/19254203/350315759-bcbfcc5d-66f9-4026-8847-da2807ca4879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNzg4MDEsIm5iZiI6MTcyMTM3ODUwMSwicGF0aCI6Ii8xOTI1NDIwMy8zNTAzMTU3NTktYmNiZmNjNWQtNjZmOS00MDI2LTg4NDctZGEyODA3Y2E0ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDA4NDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMDFkYjRlN2FmZTc3OWQxYjAyMTI0OTIyNjk3MmJhZDU3ZGU2ZDQwZWIxOWUxMzNmMGFjMzkyMTI1MzIwZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BpoiCjX670HUIAAtDaVBTmtbaII936Cmyqey1LLJKeU)

Samozřejmě popisek, kdo je na té kazetě, je k věci. Otázka je, jestli je v originále jen takhle jméno, nebo něco dalšího.

**Comment by PetrCejpek** [comment]
> Našiel som v Main.sc názvy týchto náhrávok. Prepíšem to na "Nahrávka -ové" či Záznam?

Super, v tom případě bych dal: **Nahrávka s Michelle Milkenovou**, **Nahrávka s Lahodnou Lanou**, **Nahrávka s Chi Chi Lambadou**

**Comment by miracleflame** [comment]
Tento nový skript znehodnotí uložené pozície, takže na test bude treba novú hru. Na dnes už nechystám zmeny skriptov, budem sa pýtať na fóre.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/f41973a6-7f79-4bc2-8f10-433e8a4f5d77)
Otestováno.
