### ISSUE TITLE
Text je v angličtině

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#104]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/12f2420d-a803-407b-928a-57c2bdf07da0)

Tady je text v angličtině. Nejspíš bude opět problém s *.src patch souborem?

**Comment by miracleflame** [comment]
Pravdepodobne áno, pokiaľ máš nejaké scr súbory, tie prepíšu všetky skripty danej scény... takže ich treba nahradiť scr súbormi, ktoré som posielal naposledy.
V tejto scéne som to videl preložené.
