### ISSUE TITLE
A to, ty!

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#105]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/b41f388c-bb86-4b08-9539-5a48590a89d0)

Při interakci s ventilátorem:
**Bojíš se zapnout ventilátor bez ochranného oděvu.**
**A to, ty!**

Přepsat druhou větu:
**A to, ty!** -> **(To jsi celý ty!)**

**Comment by miracleflame** [comment]
Toto som už opravoval tu v 180.tex 0e257abb9882bbcc0751826ce0882cea4421cc12
And it, you! by sa doslovne dalo preložiť A ono, tebe!
Preložil som On tebe taky!

v origáli je po interakcii "turn on" ako dvojzmysel nažhaviť, to by som navrhol zaimplementovať, aby to spätne ladilo s #11 
Bojíš se nažhavit ventilátor bez ochrany.

**Comment by PetrCejpek** [comment]
Jo, jo, mě to pak došlo, že to asi bude něco s turn on. :-) Nech to, jak říkáš.

**Comment by miracleflame** [comment]
Dal som
^Bojíš se nažhavit ventilátor bez ochrany.
^(On se toho bojí taky!)
