### ISSUE TITLE
Magnetofon v pracovně

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#106]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/31765a8c-7051-4d4d-ac5b-758a652f1077)

Upravit poslední položku na: **{\_\_\_\_Na promenádě\_\_\_\_}**

Upravit **Vysunout** na: **{< Vyjmout kazetu >}** (je to v tom souboru 2x, protože jsou dvě obrazovky)

Pak ještě otázka, jestli překládat názvy těch skladeb. Tady myslím, že by možná ani nevadilo, kdyby něco bylo přeložené a něco ne.

**Comment by miracleflame** [comment]
No doprdele, pamätám si, že Na promenáde som už vycentroval a fungovalo to dobre.. nejako sa to po teste nedostalo do repozitára :/
Ja som za preklad, ide o vymyslené názvy songov soundtracku hry, aby mal hráč predstavu, z akej scény hudba je.

**Comment by PetrCejpek** [comment]
{\_\_Larryho píseň\_\_\_}
{\_Record des Rever\_}
{\_Desmondovo téma\_\_}
{\_\_Silas Scruemall\_\_}
{\_\_Závěrečné téma\_\_\_}
{\_\_\_Udělej mi to\_\_\_}
{\_\_\_Udělej si to\_\_\_}
{\_\_Udělej to tvrdě\_\_\_}
{\_Michellina píseň\_\_}
{\_\_\_\_\_Shill-enství\_\_\_\_\_}
{\_\_\_\_\_Sex a ságo\_\_\_\_\_}
{\_\_\_\_Na promenádě\_\_\_\_}
{\_Práce ve studiu\_\_}
{\_\_\_\_Nadechni se\_\_\_\_\_}
{\_\_\_Zlobivý holky\_\_\_\_}
{\_Kdo je teď nahoře?\_}
{\_\_Trampovo kasino\_\_}
{Ivana a její brusle}
{\_\_\_\_\_K-RAP rap\_\_\_\_\_}
{\_\_\_\_\_K-RAP debata\_\_\_}
{\_\_\_\_K-RAP rock\_\_\_\_\_}
{Doktor vám je vytlhá\_}
{\_\_Chi Chi a já já\_\_}
{\_\_\_\_Salsa jede\_\_\_\_\_}

**Comment by miracleflame** [comment]
Tu som si všimol tie témy. V zmysle skladby sa Theme zvykne prekladať ako **Znělka** ..nedám tam radšej znělky?

**Comment by PetrCejpek** [comment]
No, záleží, pokud se to tam vejde. Ale mělo by. Takže:
**{Desmondova znělka\_}
{\_Závěrečná znělka\_\_}**
