### ISSUE TITLE
Centrum Blecchnaven

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#108]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/062b7af8-0156-4329-8903-1d063e56fe79)

Tady mám pocit, že je nějaký pun v názvu toho centra, ale nedokázal jsem na internetu nic najít. Nějaký nápad?

**Comment by miracleflame** [comment]
Dopátral som sa týchto dvoch významov, o ktorých sa domnievam, že sú tu mienené
https://www.urbandictionary.com/define.php?term=blecch
https://www.namious.com/m/naven

**Comment by miracleflame** [comment]
napadlo mi Centrum Traditajbl

**Comment by PetrCejpek** [comment]
Asi to nakonec přeložím jako **Nechuťáci**.

**Comment by miracleflame** [comment]
Centrum Nechuťáci?

**Comment by PetrCejpek** [comment]
No. :-D Nechtěl jsem, aby to bylo prvoplánově nějak spojené s těmi homosexuály na začátku. Takhle mi přijde, že to bude víc vyjadřovat "co ti lidi dělají" než "co jsou".

Navíc mám pocit, že to asi nějaký odpor ke skupině lidí vyjadřovat nemá.

**Comment by miracleflame** [comment]
No, ono je tam tá referencia na heterosexuálne páry, takže to už by bolo moc na pílu.
