### ISSUE TITLE
návrh prekladu "...největší fanoušek" z rm180.sc

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#11]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/d8649445-236b-454c-8f78-3a3d56558af4)

pozn.prekl.?

**Comment by PetrCejpek** [comment]
Můžeme se pokusit vymyslet vtip na **větrák** v češtině.

Návrh překladu:
**Lepší tenhle větrák než zvětralé pivo!**

**Comment by miracleflame** [comment]
Síce mimo misu ale lepšie ako nič.. A čo trebarz
"To je ale statný fukéř!" 
..to by aj ladilo s teou druhou replikou, kde sa bojí (nažhavit) On tebe taky #105

**Comment by PetrCejpek** [comment]
Ale fukéř/fukýř/futeř je podle tohoto článku http://nase-rec.ujc.cas.cz/archiv.php?art=3661 spíš vichřice. Možná myslíš fukar, ale to je spíš ten stroj na listí.

**Comment by miracleflame** [comment]
Včera som počul v českých Simpsnoch SE34 EP03 hneď na začiatku výraz "starou fuknu" ako narážku na polnici.
Hneď som si spomenul na toto :D 
Aktuálne tam je teda
Tohle je tvůj největší fukar!
Navrhuješ iné?

**Comment by PetrCejpek** [comment]
Ještě mě napadlo něco ve smyslu: **"Duj, větře, duj a rvi mou kštici!"**, nebo **"Zapni ho a bude fičák!"**

**Comment by miracleflame** [comment]
No kľudne, je to na tebe.

**Comment by PetrCejpek** [comment]
Tak tam prosím dej: **"Duj, větře, duj a rvi mou kštici!"** (**180.scr**)
