### ISSUE TITLE
Nepochopený vtip

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#110]
Když vezme Larry na letišti čtvrťák z misky na milodary, objeví se hláška: **Tady končí tvá šance na telemaraton "Larryho děti"!** Moc jsem nepochopil ten vtip. Nějaký nápad? Jako že je Larry tak zoufalý, když krade milodary, že nikdy nebude mít děti?

**Comment by miracleflame** [comment]
A telethon (a portmanteau of "television" and "marathon") is a televised fundraising event that lasts many hours or even days, the purpose of which is to raise money for a charitable, political or other cause.
...
Ale aj tak mi pointa nejako uniká.

**Comment by miracleflame** [comment]
Charitativní telemaraton "Larryho děti" už tedy nebude potřeba.

**Comment by PetrCejpek** [comment]
Takhle už to dává celkem smysl. Možná bych tam ještě něco přidal, aby bylo jasné, že je to o těch penězích:

**Takže peníze teď máš, charitativní telemaraton "Larryho děti" už tedy nebude potřeba.**
