### ISSUE TITLE
Překlep a formulace

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#111]
Larry v letadle při jednom snu:

**Ve snu sleduješ vášnivou Patti při rockovém koncertu před zrcadlícím vodní nádrží Tádž Mahalu!** -> **Ve snu sleduješ Vášnivou Patti při rockovém koncertě před zrcadlící se vodní nádrží u Tádž Mahalu!**

**Comment by miracleflame** [comment]
skoro som to vychytal tu e0133a936fd6825165b05eb8f810a9f597cd18a4
