### ISSUE TITLE
now boarding preklad grafiky

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#113]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/316078bb-4eb8-4858-abe5-63438ac3e9cf)

**Comment by miracleflame** [comment]
@PetrCejpek Nastupovat?

**Comment by PetrCejpek** [comment]
Nejlepší by asi bylo **PROBÍHÁ NÁSTUP**, ale to se tam nejspíš nevejde. Takže **NASTUPOVAT** je dobré.

**Comment by miracleflame** [comment]
[NASTUPOVAT](https://streamable.com/q1vowi)
