### ISSUE TITLE
Rodový konflikt v limuzíne 200.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#12]
Niektoré akcie tu môže robiť aj Larry aj Patti.

^Ačkoliv by ses ráda s tou rybkou pomazlila, jí by se to určitě nelíbilo.
návrh: Ačkoliv je ta rybka pomazlení hodná, jí by se to určitě nelíbilo.

![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/a25b7fb6-4f50-4adb-b949-bfec8da658f8)

**Comment by PetrCejpek** [comment]
Podobný problém:
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/0941d6fd-0645-4dfd-a502-a68685de9b58)

**Comment by miracleflame** [comment]
Toto som priebežne v niektorom commite vyššie vyriešil odstránením ", abys mohl"
