### ISSUE TITLE
značka?

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#13]
Na mnohých miestach sú rôzne cedule, pútače a tabule. obvykle je to preložené ako značka... od sign.
Ako to opravíme?

**Comment by PetrCejpek** [comment]
Asi by možná bylo lepší **cedule**.

**Comment by miracleflame** [comment]
Na letiskách som dával cedule. Nápisy som dal na budovách Shil A Trampovo kasíno a nastupný nápis na letisku.
Hodné testu.

**Comment by PetrCejpek** [comment]
Co jsem otestoval, je to v pořádku.
