### ISSUE TITLE
D D D

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#132]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/1590c24d-e725-46a1-a079-b3aacf94b0c7)

Zajímalo by mě, co tam je v originále místo toho D D D.

Pak bych změnil název předmětu -> **Kotoučová páska**

**Comment by miracleflame** [comment]
V origináli je to isté D D D

**Comment by PetrCejpek** [comment]
V tom případě asi ok.
