### ISSUE TITLE
POLICEJNÍ VÝSTROJ

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#138]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/7c26e208-6465-4cbb-8914-c0ad73b7b83a)

Divné zarovnání nadpisu.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/17491522-6491-4d1b-9a2b-4775255e6f45)
Tenhle nadpis je pořád špatně zarovnaný. Tady to ale spíš způsobuje to zalamování textu v tom odstavci. Asi bych úplně umazal ty tabulátory/mezery, které jsou před tím nadpisem. Taky je možné, že to dělá interpreter - myslím, že text se od minula nezměnil a DOSbox (úplně první obrázek v tomhle issue) to zarovnal jinak.

Nebo je možnost, že to dělá tabulátor vs. mezery. Pokud bychom to chtěli opravdu zarovnat, možná bychom si mohli pohrát s pevnými mezerami před i za nadpisem.

**Comment by miracleflame** [comment]
Tiež v tom nevidím zmysel nejako to centrovať. Zarovnal som to k okraju, ak môže byť, rovno zatvor.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/8b6040a5-2815-4555-b13e-fed20dc4a1d9)
Otestováno.
