### ISSUE TITLE
Návrh odstránenia ráno/odpoledne rm258.sc

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#14]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/2354b19e-1f23-405d-a54b-96e38d45b2e6)

Navrhujem text úplne odstrániť, lebo je zbytočný. Na pochopenie či mechaniku protipirátskej ochrany to nemá nijaký vplyv.

![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/8925342a-021c-4218-8a18-c2ae6e1555b0)

**Comment by miracleflame** [comment]
odstránené v commite vyššie

**Comment by miracleflame** [comment]
@PetrCejpek máš sem prístup? Neumožňuje mi asajnovať na teba.

**Comment by PetrCejpek** [comment]
> @PetrCejpek máš sem prístup? Neumožňuje mi asajnovať na teba.

Vlastně nevím, co to znamená assignovat.

Jinak můžeme odstranit, případně přepsat na:
**ráno** -> **dop**
**odpoledne** -> **odp**

**Comment by miracleflame** [comment]
Tu vpravo vidno
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/fc652f79-ed78-442b-9b20-56df59878827)

Na kom je tiket naasajnovaný, od toho by mala prísť ďalšia akcia na tikete. Je to užitočné v prehľade všetkých tiketov, keď je toho veľa ako teraz, človek sa nemusí prehrabávať tým, čo nečaká naňho.

dop/odp by aj tak bolo úplne na hrane obrazovky, ktorá je zaoblená ináč než text na nej, nepôsobí to dobre a ten extra text fakt ničomu nepomáha, skôr by českého hráča zbytočne miatol - na karte s ochranou sa to nijako nerieši. 
Bez textu to mám otestované a funguje to dobre.
Tak ja to beriem tak, že môže byť táto varianta a tým pádom je to už implementované a otestované - zatváram.
