### ISSUE TITLE
Přebývá střížka

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#140]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/0e5e4fd3-bfc5-409f-8a3c-bc1cedd85035)

Přebývá stříška.

**Comment by miracleflame** [comment]
Toto bolo v tex súbore 280 opravované už v hromadách 1aea113267e2e6989b8ce7b29e84c337e9ef23fa
