### ISSUE TITLE
Chybí překlad

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#143]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/69006a57-072b-4b84-a324-c09fa1ce0130)

chybí překlad (nejspíš problém src souboru)

**Comment by miracleflame** [comment]
áno toto je určite problém nekompatibilnej pozície
