### ISSUE TITLE
the_Piano_Pit_Manager of Talker v rm405.sc

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#15]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/89a63b3d-9e05-4850-ac47-14bcb81bbbbf)

**Comment by miracleflame** [comment]
preložil som ako Provozní Pianové Nory

**Comment by PetrCejpek** [comment]
Myslím, že jsem to překládal jako Pianová díra. (někde je to v textu) Zároveň podle mě v češtině má být velké jenom P, d má být malé.
