### ISSUE TITLE
Přeházená jména speakrů

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#150]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/56ad6aeb-9e9e-4eb7-b473-f70684490acf)
U tohohle rozhovoru se mi stávalo, že bylo špatně nadepsané, kdo kdy mluví. (jméno speakera neodpovídalo)

**Comment by miracleflame** [comment]
Zareportované a fixnuté https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/17
