### ISSUE TITLE
Divné znaky v rozhovoru

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#151]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/4c6bacaf-a2ce-4739-9dbf-4e815daf34aa)
Divné znaky v rozhovoru

**Comment by miracleflame** [comment]
Najskôr bude súvisieť s https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/17
