### ISSUE TITLE
Rod

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#152]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/3e1d99cb-2588-4093-8f24-7830fc7b7a6b)

Nutno přepsat rodově neutrálně (možná už to tu bylo).

**"Bože," pomyslíš si, "nezáleží na tom, kde člověk je, jakou půjčovnu limuzín si vybere, nebo kterého řidiče si vybere... všechny limuzíny vypadají stejně!"**

**Comment by miracleflame** [comment]
Túto repliku má len Larry, opravené v dalsi rodovy konflikt v limuzine [#12](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/12)
