### ISSUE TITLE
Zarovnání nápisů

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#155]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/488eeb0b-239f-44a4-9979-4b0e5d058499)

Špatné zarovnání nápisů. Možná bude taky problém s proměnlivou šířkou té tabulky.

**Comment by miracleflame** [comment]
No ono je to aj v origináli takto
^__allowe____Supplies________827
^Hell____Industries___________301
^__uck_You___________________702
^des_Rever_Records_________900
^Shi____Heads________________400
^AeroDork Corp._____________501
^Big_Butt____s_Inc.__________251
^Hard_Di__k_Service________601

akurát, že originál mi evokuje, že niektoré písmená chýbajú, naproti prekladu, kde to je proste nelogicky rozhodené.
Ako by to malo vyzerať, o čo tam má ísť?

Inak tento editor automaticky maže opakované medzery, takže navrhujem podčiarkovníky

**Comment by PetrCejpek** [comment]
Rozumím. Ona ta písmena chybí schválně. A mám pocit, že na obrázku chybí správný počet, že to nic nevynechalo - tohle je teda v DOSboxu, otázka teda je, co s tím udělá Scummvm.

Pointa vtipu - Patti to komentuje, že lidem, kteří dělali ty nápisy, očividně došla písmenka. To znamená, že vynecháním těch písmen se vytvoří jiná slova (případně to má evokovat jiná slova), někdy až přisprostlé názvy.

Třeba z **Big Buttons Inc.** vznikne **Big Butts Inc.** (velké zadky), nebo to poslední vynechání písmena v **Hard Disk Service** má evokovat **Hard Dick Service** (servis pro tvrdé penisy).

Takže i v překladu je úmysl - dalo mi to docela dost práce vymyslet, aby to nějak fungovalo v češtině. :-D

**Comment by miracleflame** [comment]
Je mi to jasné, akurát nie všetky riadky si viem domyslieť, aké tam mali byť pôvodné slová.
Keby si mi to prepísal bez vymazaných písmen, pokúsil by som sa to správne pozarovnávať.

**Comment by PetrCejpek** [comment]
Je to pak určitě někde v textu, když to Patti komentuje (soubor 620.cs5). Mělo by to být takto:
ZÁSOBY NA HALLOWEEN
POZDRAV Z MÉHO SRDCE
NA PTÁKY JSME KRÁTKÝ
DES REVER RECORDS (nezměněno)
NÁŠ LODNÍ NÁBYTEK
AEROBLB, CORP. (nezměněno)
VELKÉ KNOFLÍKY, S.R.O.
HARD DISK PODPORA

**Comment by PetrCejpek** [comment]
Při mém včerejším testu, to ještě nebylo ono. Upravil jsem to v tex souboru, ale ještě bych možná vyzkoušel, co s tím udělá interpreter.

**Comment by miracleflame** [comment]
Hmm, na zobrazovanie tex stringov, myslím, nemá interpreter vplyv... ak teda myslíš 0.scr (Main.sc)

**Comment by PetrCejpek** [comment]
Scummvm:
![image](https://github.com/user-attachments/assets/f38492cf-ffbd-41e0-b435-da68b145f9a1)

DOSbox:
![image](https://github.com/user-attachments/assets/c74cbb66-bf1e-40a6-86cf-e7283a652cee)

Ok, je to stejný. Já měl totiž pocit, že interpreter zarovnával jinak ty životopisy a ignoroval nějaké mezery. :-)
