### ISSUE TITLE
Problém s koulemi 320.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#16]
Letuška pristihla Lartyho ako zo sna stíska balíčky s orieškami,
^"Why, Mr. Laffer! Is there a problem with your nuts?"

![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/11c9c5b7-587c-41cd-bafb-b27f9776c81b)

**Comment by PetrCejpek** [comment]
Tady jsem očividně nepochopil ten vtip, nebo že mačká oříšky. Asi mě zmátlo to, co se píše v souboru předtím (něco o mokrém klíně, nebo co) :-D

**Comment by miracleflame** [comment]
Ja sa len zamýšlam, aké by bolo najlepšie znenie
"No teda, pane Laffere! Je snad nejaký problém s vašima oříškama?"

**Comment by PetrCejpek** [comment]
Co takto: **Pane Laffere! Je snad s vašimi oříšky něco v nepořádku?**
