### ISSUE TITLE
Oh, OH, OOOOOHHHHHH

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#160]
Jedno h by mělo být velké. (Pattiin sen)

**"Oh, OH, OOOOOHHHHHH!" křičíš ze sna! "Miluju, když tohle děláš!"**
->
**"OH, OH, OOOOOHHHHHH!" křičíš ze sna! "Miluju, když tohle děláš!"**

**Comment by miracleflame** [comment]
Myslím, že to je úmysel (aj v origináli) na vyjadrenie 1-2-3 gradácie vzdychov.

**Comment by PetrCejpek** [comment]
Aha, máš pravdu. :-)
