### ISSUE TITLE
Kdykoli/kdykoliv

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#165]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/1c497d3a-ca5f-47dd-bbcf-5983fa85d69e)

**kdykoliv**

**Comment by miracleflame** [comment]
To si už sám reportoval a ja opravoval, nechce sa mi to hľadať.
