### ISSUE TITLE
 Tak co, chceš zavolat tu káru, nebo ne?

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#169]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/4876f4d2-8bb4-4ba4-afb7-12bdf9639a3a)

Originál je kostrbatý, ale nejspíš je to přízvuk a ne proto, že by to byl cizinec.

Návrh na úpravu:
**Tak co, chceš zavolat tu káru, nebo ne?**

**Comment by miracleflame** [comment]
Opravené ináč v a9c4583f86741658f450b179409b87e34c3e84d1

**Comment by PetrCejpek** [comment]
Ještě na to navazuje:
**"Ano, prosím... ale mohl byste to vrátit?"**

Tady jsem nějak nepochopil (ani podle originálu), co chce vrátit. Spropitné mu dává až potom. Nějaký nápad?

**Comment by miracleflame** [comment]
Vítačka dá Larrymu úvodný kredit a Vrátny ho zoberie s akýmikľovek nahranými kreditmi späť pred odchodom zo scény.

**Comment by PetrCejpek** [comment]
Ale to "Ano, prosím..." je Larryho odpověď na to, že chce zavolat limuzínu, ne?

**Comment by miracleflame** [comment]
"could you make it back in" podľa mňa by sa tam hodilo
"ale můžete sebou hodiť?"

**Comment by PetrCejpek** [comment]
Jo, super. :-)

**Comment by miracleflame** [comment]
Inak k
Návrh na úpravu:
Tak co, chceš zavolat tu káru, nebo ne?

Nemal by vrátný vykať? Ja viem, že je "priateľský" a preto ten preklad, ale to vykanie by tam podľa mňa sedelo viac... okrem toho, že v ostatných replikách vyká.

**Comment by PetrCejpek** [comment]
Měl by vykat. Už jsem to otestoval ve hře.
