### ISSUE TITLE
Stříbrné dolary

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#177]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/80ca3a3a-4432-4251-aed1-3ee62ded33d3)

Tady se doplňuje proměnná %d a %s, ale v češtině ta druhá asi nemá význam.
**Máš %d stříbrných dolarů%s, ale toužíš jich mít mnohem, mnohem víc.**

Úprava:
**Máš %d stříbrných dolarů, ale toužíš jich mít mnohem, mnohem víc.**

**Comment by miracleflame** [comment]
Mhm, asi tam môže nastať aj prípad jedného dolaru. Nechceme to preformulovať na niečo ako počet dolarú: alebo tak aby to aj s jedným vyznelo fajn?

**Comment by PetrCejpek** [comment]
On není problém jen 1, ale i 2-4. Navíc je to i jinde. Například: **Vložíš do automatu všech svých %d stříbrných dolarů.** Psát něco jako **Máš stříbrné dolary v počtu %d** mi přijde trochu kostrbaté. Asi to jinak nepůjde.
