### ISSUE TITLE
Chi Chi trocha nelegální činnosti 915.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#18]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/de4d48a4-bde6-4fdf-a01b-19027514afee)

**Comment by miracleflame** [comment]
zatiaľ navrhovaná oprava
Ach Larry, doufám, že vám nepřekáží nelegální záležitosti!

**Comment by PetrCejpek** [comment]
Ano, něco tam chybí. Jak je to ale myšleno? (ve hře jsem do tohohle bodu zatím nedorazil) Co si vybavuju z korektury, tak jsem to pochopil tak, že Chi Chi je ilegální migrantka a nemá povolení k pobytu. Takže můj překlad by byl: **"Ach, doufám, že vám nevadí trochu ilegální činnosti, Larry!"**
Tvůj překlad mi evokuje, že se na něj Chi Chi lepí ňadry (a to jsou ty ilegální záležitosti). Což vlastně může být, jen nevím kontext. :-D

**Comment by miracleflame** [comment]
Je to presne tak a otvorene koketuje, takže ide o dvojzmysel, preto som to naformuloval tak, aby to neevokovalo primárne len tú ilegálnu imigráciu.
Inak dialóg potom pokračuje, kde sa otvorene hovorí už o ilegálnej imigrácii a že by bola ochotná urobiť čokoľvek za riešenie.

**Comment by PetrCejpek** [comment]
Jo, tvoje verze je dobrá. Nech to teda takto. :-)
