### ISSUE TITLE
Překrývající se text

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#186]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/fb58f616-df27-45d5-bbf7-ab58e3b60845)

Tady se překrývá text s čísly, která se tam doplňují. Měl by to být soubor 720.tex. Nevyřešilo by před ta čísla (%d) dát nějaké mezery, aby se to posunulo?

Taky by se dal překreslit text na těch tlačítkách, ale to je jen takový detail, protože k nim jde vyvolat nápověda.

**Comment by miracleflame** [comment]
Neni problém prekresliť. Len aby sa tam preklad vmestil. Návrhy prekladu?

**Comment by PetrCejpek** [comment]
No právě, aby se to tam vešlo... Myslím, že se nevyhneme tomu, aby to někde bylo na dvou řádcích, jako je to u toho tlačítka vpravo.

Návrh:
DEAL -> ROZDAT
HOLD -> NECHAT
CASH OUT -> VYPLATIT

**Comment by miracleflame** [comment]
To je dlhé, aj pri najmenších písmenkách, čo zaberú 3 pixle +1 na medzeru
dalo by sa to trochu skrátiť
ROZDEJ (J by šlo na dva pixle)
PODRŽ
VYBER
?

**Comment by PetrCejpek** [comment]
To by šlo. :-)

**Comment by miracleflame** [comment]
Zatiaľ takto
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/06dbaaf0-93e1-441f-a5fc-7cb8b3dce0b3)

**Comment by PetrCejpek** [comment]
Dobrá práce. :-) Ještě bych zkusil změnit VYBER na VYPLAŤ (takhle bude jasnější, že jde o peníze a netýká se to těch karet). Zkusil jsem:
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/91ef8c6e-3476-46af-8398-458f984d8b6b)

**Comment by miracleflame** [comment]
No výborne :) síce na milimeter, ale stále krajšie V a bez toho hnusného B.
Mohli by sme sa pobaviť o zopár záležitostiach... ako to teraz nahráš na GH a pod. som na Discorde

**Comment by miracleflame** [comment]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/90b390ac-60e3-4a86-815a-a1f6db2aa057)

**Comment by PetrCejpek** [comment]
Já jsem ještě v práci, tak řekněme v 19:30 na Discordu?

**Comment by miracleflame** [comment]
otestované
