### ISSUE TITLE
Ubrousek z dentálnej ordinácie je v skutočnosti šála 

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#19]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/d5a6d79c-4dc3-49ca-b299-8d8dc6ad8a23)

**Comment by miracleflame** [comment]
Prosím o kontrolu skloňovania a podobne vo všetkých súboroch commitu.

**Comment by PetrCejpek** [comment]
A je to určitě šála? Já prvně myslel, že je to to samé, co Larry našel v životopisu (což teda není). Podle překladače se nicméně zdá, že je to nějaké prostírání (taková ta krajka, která se třeba dává pod vázu na stole jako ozdoba).

**Comment by miracleflame** [comment]
Obávam sa, že máš pravdu, z tohto popisu, aj keď na tom stolčeku vpravo to tak nevyzerá.
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/b2a9c5e3-c24e-4cdd-93da-e13b39af8bce)

To slovo sa skloňovalo asi na 100 rôznych miestach omg, ale vďaka Gitu to viem veľmi ľhko revertnúť do pôvodého stavu. Vykonám?

**Comment by PetrCejpek** [comment]
Ano, prosím.
