### ISSUE TITLE
Padání hry

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#195]
Po závěrečném snu, který se Larrymu zdá v letadle, a který se přerodí v rozhovor s inspektorem Desmondem, mi hra spadne. Problém bude nejspíš opět v titulku, který se má zobrazit (soubor 380.tex):
**Najednou,
let mířící na západ
míří na jih!**

Tenhle problém se mi ale při hraní na DOSboxu podařilo přeskakovat. Možná už je to ale opravené - říkal jsi, že jsi to vyřešil.

Chybová hláška:
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/2a9b924d-b1f7-4a09-933b-c15efccd302c)

Mimochodem, stejná hláška se mi objevovala, když jsem se pokoušel přejmenovávat *.src (patche) soubory (ty dělaly to, že se někde pořád zobrazovala angličtina). Hra mi pak spadla taky s touto hláškou.

**Comment by PetrCejpek** [comment]
No, padá mi to bohužel i ve Scummvm. Vyhodí to tuto hlášku:
![image](https://github.com/user-attachments/assets/72b3887e-073e-42ad-a7e5-30818848560f)

Problém teda nebude v titulku (protože ten jsem na malou chvíli zahlédl, než se přes to hodila ta konzole), ale nejspíš někde ve skriptu za tím (buď hned v 380.src, ale spíš 385.src nebo jinde)

**Comment by miracleflame** [comment]
Máš možnosť vyskúšať túto scénu bez 380.scr? Alebo pozdielať uloženú pozíciu s tou verziou skriptov, čo treba?

**Comment by PetrCejpek** [comment]
Musím tam ve hře znova dojít, nezálohoval jsem si Main, takže nemám teď kompatibilní save. :-/

**Comment by miracleflame** [comment]
Dosť dobre funkčný workaround zatiaľ je odstrániť 380.scr

Skúšam prísť na fix pomocou SCI fóra
https://sciprogramming.com/community/index.php?topic=9235.0
