### ISSUE TITLE
Pouzitie predmetu na lubovolne miesto

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#196]
Tato vec je stale nevychytana

![obrázok](https://github.com/user-attachments/assets/ade3d3a7-7f32-40f9-a133-0591281752b3)

**Comment by miracleflame** [comment]
Zatiaľ som dal
%s na tomto místě nedělá nic, zkus najít jiné místo.

**Comment by PetrCejpek** [comment]
Není to špatné, ale %s úplně na začátku není moc dobré, protože bude věta začínat na malé písmeno. Obecně by se asi mělo řešit i jednotné a množné číslo, ale myslím, že žádný předmět v inventáři v množném čísle není.

Návrh na úpravu:
**Tady %s k ničemu nebude, zkus najít jiné místo.**
