### ISSUE TITLE
Patti v laboratoři FBI blbne

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#198]
Když je Patti v laboratoři FBI, je to celé nějaké zabugované (měly by to být soubory **430.sc** a **440.sc**).

-	Pokud kliknu kurzorem oka nebo mluvení na jakoukoliv postavu kromě velitele Magora, kurzor se změní na ruku a nejde nic dělat (vlastně všechny ikony v horní liště zešednou, jako kdyby měla proběhnout nějaká animace, ale nic se nestane)
-	Patti chodí divně – místo animace chůze se otáčí a přitom posouvá
-	DataMan a DataPaky nejdou vzít (nefunguje na ně kurzor ruky)
-	Nejde opustit budovu (kurzor ruky nefunguje na východ/dveře), takže nelze pokračovat dál ve hře. K doktorovi Hopianovi na prohlídku jít ale šlo.
-	Zajímavé je, že na ostatní předměty v místnosti ruka funguje

**Comment by miracleflame** [comment]
Tak toto je hodne hnusný bug, aj na analýzu kvôli nekompatibilite sejvov... Ale konečne sa mi podarilo zúžiť oblasť na skripty 0-22
tak hádam to už nepotrvá dlho

**Comment by PetrCejpek** [comment]
Držím palce.

**Comment by miracleflame** [comment]
Je to Main.sc - 0.scr
a to je hodne zlé.

**Comment by PetrCejpek** [comment]
Ou, shit. Nepůjde to vysledovat z nějakých posledních změn? Ta úprava asi nebude víc, jak měsíc nebo 2 týdny stará.

**Comment by miracleflame** [comment]
Tu je celá história súboru a z môjho pohľadu sú to skôr bugfixy než že by sa tam mohlo niečo rozbiť.
https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/commits/master/src/Main.sc

Obávam sa, že to je chyba priamo dekompilácie, ale už nemám silu to overiť.
Cez DosBox to neblbne, možno preto máš dojem, že to tam je iba chvílu.

**Comment by PetrCejpek** [comment]
Aha, je fakt, že teď to testuju na scummvm. :-/

**Comment by miracleflame** [comment]
Sleduj tie rady :')

https://sciprogramming.com/community/index.php?topic=9233.0

**Comment by PetrCejpek** [comment]
No, čím víc to čtu, tím víc se v tom asi ztrácím. :-D Každopádně řešení asi existuje, jestli jsem to pochopil správně.
