### ISSUE TITLE
Palubní lístek vs. letenka (grafika)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#199]
Především oceňuji, že sis vyhrál a překreslil nějaké textury do češtiny. :-)

Nicméně - není **letenka** a **palubní lístek** něco trochu jiného? I když je fakt, že ty letušky mu říkají: "běžte si koupit letenku k automatu venku."

**Comment by miracleflame** [comment]
M.yslím, že oboje sú v origináli Boarding Pass a v princípe ide o to isté.

**Comment by PetrCejpek** [comment]
https://www.flyradar.cz/letectvi/boarding-pass/

Myslím, že letenka bude spíš _(flight) ticket_. Ale jinak to bude asi pro tu samotnou hru jedno.

**Comment by miracleflame** [comment]
Je pravda, že na ATM termináli sa píše vemte si palubní lístek a vyleze papierik s nápisom letenka, tak neviem, ako s týmto naložiť. Prekresliť papier z ATM neni problém, len s ikonou v inventári neviem, ako to tam do tých pár pixlov narvať.
