### ISSUE TITLE
Gateway na letisku

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#20]
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/b3e8b35f-56cb-49d9-94ff-c99929b1f28d)

**Comment by PetrCejpek** [comment]
Kde je problém? Brána vs. gate? V češtině se brána používá. Možná by šlo ještě **odletová brána**.

**Comment by miracleflame** [comment]
Asi ma to tam zmiatlo, nie som zvyknutý vidieť na letiskách niečo iné ako gateway.
Dám tam teda odletová brána, aby issue nevyšla nazmar.
