### ISSUE TITLE
Patti telefonuje v limuzíně - špatná formulace doplňujících se stringů

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#200]
![image](https://github.com/user-attachments/assets/9165edfc-740a-4ce0-84a3-8719a7f2c4d0)

Když chce Patti telefonovat v limuzíně a zmáčkne na číselníku 0, generuje se něco jak hláška operátora (viz obrázek). Doplňují se tam stringy podle toho (asi), v jaké lokaci se hráč nachází. (nejspíš půjde vyvolat podobná situace s Larrym, například s telefonem u zubaře, nebo ve vstupní hale Hard Disk Café).

Zkoušel jsem sám updatovat src soubor, nicméně asi něco dělám špatně, ve hře mi to padá. Nechám to teda radši povolanějším rukám.

Postižené soubory:
**PushButton.sc -> 20.scr** (důležité je u těch stringů dodržet tu čárku a mezeru před)
_(if (== global2 200)
    { plavbou po řece Potomac}
else
    (switch global160
        (1 {, protože nás právě přepadli})
	(2 { krmením automatů})
	(3 { ležením na pláži})
	(else  { sezením na záchodě!})
    )
)_

**20.tex** (tady jsem umazal mezeru mezi _zaneprázdněni_ a _%s_, aby to sedělo dohromady se stringem z 20.scr)
_"Dovolali jste se do asistenční služby pro širší oblast %s. Je nám líto, ale právě nemůžeme mluvit. Momentálně jsme zaneprázdněni (ano, zaneprázdněni%s!). Ujišťujeme vás, že váš hovor JE důležitý; jenom ne pro nás!"_

**Comment by miracleflame** [comment]
![obrázok](https://github.com/user-attachments/assets/113723ee-7b2d-4258-9c75-c880ef152e84)

takto je to v Miami, je tam nejaké zlé skloňovanie asi dopĺňanej činnosti

**Comment by PetrCejpek** [comment]
To je právě ono, proto by to bylo potřeba přepsat na to, co jsem psal výš, čili **{leží na pláži}** na **{ ležením na pláži}**, atd.

**Comment by miracleflame** [comment]
Trochu som to preformuloval, pozri prosím, či môže byť..

**Comment by PetrCejpek** [comment]
Je to dobré, jen s tím přepadením mi to přijde trochu kostrbaté. (ale to **vylehávání** a **vysedávání** je lepší než to, co jsem navrhoval :-) ). Přepadení bych dal tak, jak jsem navrhoval já.

**Comment by miracleflame** [comment]
Aha, ospravedlňujem sa, ja som nejaký roztržitý a hlavne nezdravý, prehliadol som navrhovanú zmenu. Hlavne som chcel toho čo najviac stihnúť, aby si mal na cestu z Nemecka pripravené... 
Chápem už aj tie medzery, takže som opravil a aj medzery pridal.

**Comment by PetrCejpek** [comment]
Zrovna jsem na to tady koukal ve hře a testoval. :-D Už jsem chtěl psát.

**Comment by miracleflame** [comment]
Všetko dobre
