### ISSUE TITLE
Revertování změn ve skriptech nejspíš vrátilo některé úpravy názvů

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#201]
Mám pocit, že revertování změn ve skriptech vrátilo na některá místa jiné názvy/jména speakerů. Podle všeho soubor **19.scr**.

![image](https://github.com/user-attachments/assets/202963eb-6e32-49ea-aec0-24c407a50d5d)
To jméno má být správně **Vrátný**. (Mám mlhavý pocit, že už to předtím bylo správně.)

![image](https://github.com/user-attachments/assets/539da563-13b1-42e4-bda0-f73423b30019)
Tady jsme to upravil ze **šály** zpátky na **ubrousek**.

![image](https://github.com/user-attachments/assets/14454ad5-03e0-4fa0-b109-1cf205a8a45c)
Tohle překládáme jako **Diář**.

**Comment by miracleflame** [comment]
Po analýze môžem prehlásiť, že nič z toho nebolo spôsobené revertom, ale mojou nepozornosťou pri rýchlych fixoch, v skutočnosti to nebolo nikdy commitnuté (revertnuté v prípade šály, tá mala totiž dva commity a revertol som iba ten hlavný).
To posunuté Š vo fonte som už opravoval, ak sa nemýlim.. jedine, že by si ho v posledných opravách fontu posunul späť.

**Comment by PetrCejpek** [comment]
Co se týče Š, nejsem si vědom. Myslím, že jsem upravoval nějaký font do credits.

**Comment by miracleflame** [comment]
To Š si už vybavujem, to sa mi lepšie nepodarilo, buď bude o pixel nižšie alebo bude vypadať príliš tenko oproti ostatným písmenám.
