### ISSUE TITLE
Hodnota jackpotu v kasině (doplňování %d)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#202]
![image](https://github.com/user-attachments/assets/1aa20699-3cce-4005-b05e-30c350042cd2)
V kasinu se ukazuje hodnota jackpotu. Nevím, jestli je to bug, ale vypadá to podezřele. Ta hodnota by měla být asi vyšší (pamatuju si, že když jsem to hrál na DOSboxu, bylo to určitě přes 1000).

Hodnota jackpotu se zvyšuje s každou mou hrou na automatu (možná se počítá jen vyhraná, nevím určitě).
![image](https://github.com/user-attachments/assets/e05d60e8-1671-4267-bc4f-82762945b642)
![image](https://github.com/user-attachments/assets/b0ec8e02-0be9-4257-b6d2-5f058315982a)

**Comment by miracleflame** [comment]
Pekná story je za týmto bugom
https://sciprogramming.com/community/index.php?topic=9234.0

Na korektnú aplikáciu fixu je teda ešte nutné odstrániť dummy súbory, do ktorých sa ukladá heslo od hry a nová hodnota jackpotu, lebo je tam pravdepodobne uložená tá nulová +/-
