### ISSUE TITLE
Doplnění pevných mezer (880.scr)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#203]
![image](https://github.com/user-attachments/assets/225374b6-a47e-42bf-8c56-4494f505cfe4)

Tady bych opět poprosil o pomoc se změnou ve skriptu (je to **880.scr**). Pokud to půjde, chtěl bych doplnit pevnou mezeru (Alt+0160) mezi _řídící místnosti_ a _A_ (a na všechna ekvivalentní místa typu: _studio X_, _řídicí místnost X_).

**Comment by miracleflame** [comment]
Hmm, ten grafický nápis Recording by mal byť preložený 52e07062f938ba4ed6bbd023542781209b628c30

**Comment by PetrCejpek** [comment]
Podle mě přeložený je, ale jen když je aktivní to nahrávání (čili když to svítí). Jinak to asi bude pozadí scény, tedy pic soubor.

**Comment by PetrCejpek** [comment]
Je to zkompilované? V souborech nevidím, že by se dnes změnil nějaký *.scr.

**Comment by miracleflame** [comment]
až teraz

**Comment by PetrCejpek** [comment]
Otestováno.

**Comment by miracleflame** [comment]
Otváram, lebo to mám bez medzier, aj keď mi zatiaľ nie je jasné, prečo...

**Comment by PetrCejpek** [comment]
Taky jsem na to koukal. Ale ty mezery tam jsou - jen jsou malé. Když se koukneš zblízka, tak mezi znaky je jeden pixel mezera a tam, kde je pevná mezera, jsou pixely dva. Nemohla se omylem ta mezera upravit ve fontu?

**Comment by miracleflame** [comment]
S týmto ja nejako neviem pohnúť, už som pri tom zabil dosť svojho života.

**Comment by PetrCejpek** [comment]
Upravil jsem písmo, jak jsem navrhoval (znak A0 v písmu 2107), a funguje to:
![image](https://github.com/user-attachments/assets/498471f0-4f5b-4ca2-919e-02087f393ffb)
![image](https://github.com/user-attachments/assets/f99e4344-0c0b-433d-beef-34edf23cbc42)
![image](https://github.com/user-attachments/assets/2b4f106e-2f17-466e-9dd5-b54feb35b344)
![image](https://github.com/user-attachments/assets/43e74557-9a02-4da6-aa69-604c943e0542)

Za chvíli to commitnu.

**Comment by miracleflame** [comment]
Prisahal by som, že to som už skúšal... neraz. Ale zas občas mám fakt zlé dni.
Ešte musím dorobiť rm880.sc

**Comment by miracleflame** [comment]
Ok tak nemusím, zdá sa, že tam tieto medzery už boli aj keď v commite to chýba, wtf... nenávidím túto issue.

**Comment by PetrCejpek** [comment]
Rozumím, nic si z toho nedělej. Mílovými kroky jsi pokročil zase jinde. :-) Hlavně, že nám to konverguje ke zdárnému konci. :-)

**Comment by miracleflame** [comment]
otestované
