### ISSUE TITLE
Překlad grafiky - Doktor Vytlhal

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#206]
![image](https://github.com/user-attachments/assets/e5313882-fa7d-4560-8789-ef12d76844a7)
Chceme překládat i tyto nápisy? Viděl jsem, že jsi na Trampově prkenádě překresloval jména nějakého obchodu.

**Comment by miracleflame** [comment]
Táto grafika pozadia, čo je v SCIC kategorizovaná ako Pic, sa dosť problematicky upravuje, popravde som ešte na to neprišiel, ale uvidíme...

**Comment by miracleflame** [comment]
otestované
