### ISSUE TITLE
Kosmetická vada v doplňování %s názvů předmětů z inventáře

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#207]
![image](https://github.com/user-attachments/assets/d305f19a-6116-47a7-a776-e065e1254694)
Tohle je kosmetická vada, ale asi se nad tím ještě zamyslím - názvy předmětů s inventáře začínají vždy velkým písmenem. To znamená, že když se to doplní do té věty na obrázku, je velké písmeno uprostřed věty. Asi tam nějak popřeházím slovosled. Doufám, že to první %s je vždy předmět z inventáře. (**0.tex**)

Návrh překladu:
**%s a %s prostě dohromady nefungují, jak to tak vypadá...**

**Comment by miracleflame** [comment]
V skutočnosti bug palubného lístku, viď commit

**Comment by PetrCejpek** [comment]
Aha, takže _description_ se doplňuje jako %s do textu a _name_ je v nadpisu toho okna předmětu při prohlížení v inventáři.
