### ISSUE TITLE
kontrola korektúry Michelle Milken

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#209]
Musel som to poopravovať, prosím prejdi to po mňe a daj vedieť, či máš nejaké námietky či dotazy.

**Comment by PetrCejpek** [comment]
Přidal jsem pár komentářů přímo k pár řádkům těch souborů.

**Comment by PetrCejpek** [comment]
Včera jsem testoval a dneska ráno jsem commitnul pár oprav/překlepů v tomhle místě. Už by to snad mělo být v pořádku.
