### ISSUE TITLE
Dobře, zlato. Čeká na tebe nahoře. Hned pro tebe zavolám výtah. 620.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#210]
Strážný prejde veľmi rýchlo do tykania, nesedí mi to.
Možno by lepšie pasovalo
Dobře, zlatíčko. Čeká na vás nahoře. Hned pro vás zavolám výtah.

**Comment by PetrCejpek** [comment]
Máš pravdu. Opravíme na vykání. Týká se to i další věty z toho souboru:

**"Zlato, když nevíš, kam jdeš, jak to mám vědět já?"** -> **"Zlato, když nevíte, kam jdete, jak to mám vědět já?"**
