### ISSUE TITLE
Drogy 120.tex

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#211]
^"Jak víte, už od 50. let, kdy vyšly LP desky, měla naše podprahová kampaň v nahrávacím průmyslu, 'Do toho, léky', obrovský úspěch."
^"Prodej léčiv nebyl nikdy lepší a ceny zůstávají pevné, jak ukazuje tato prezentace."

Toto si opravil z drog na léky. Som si istý, že s liekmi to nemá čo robiť, ide o drogy. Samotná zápletka a investigácia je o drogách... v podprahovej nahrávke je "Just say yes", na čo Patti pripomenie, že to je presný opak toho čo hovorí Nancy Reagan - https://en.wikipedia.org/wiki/Nancy_Reagan

**Comment by PetrCejpek** [comment]
Dobrý postřeh. Pamatuju si, že jsem si při té korektuře nebyl vůbec jistý. Ale jestli jsi našel, na co to odkazuje, tak to směle přepiš. :-)
