### ISSUE TITLE
rozhodně cením

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#212]
![obrázok](https://github.com/user-attachments/assets/7adccdd3-d071-4f66-b017-fbacfc23a3b9)

Viem, že sa to medzi cool ľudmí podáva aj bez zvratného zámena, ale predsa sa spýtam, čo to tak necháme...?

**Comment by PetrCejpek** [comment]
Máš pravdu. Přepišme to na:
**ale rozhodně si cením tvé ochoty nám takhle pomoct**
