### ISSUE TITLE
Skrátiť Najednou, let mířící na západ míří na jih!

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#215]
Tento text sa obrazovkou iba mihne a zvuk jačania je tam odzačiatku... neviem, ako by som toto ošetril v skripte,
ale jednoduchšie a prepadovejšie riešenie by bolo prepísať text jednoducho na
NAJEDNOU

**Comment by PetrCejpek** [comment]
Dnes ráno jsem to tam přepsal na **NAJEDNOU...**, večer to ještě otestuju.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/f94c0566-0da9-4018-8697-e0eef94cba63)
