### ISSUE TITLE
Názvy zvukových smyček v závěrečných titulcích

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#217]
![image](https://github.com/user-attachments/assets/f1c5128c-bb86-4e08-8d98-fcc0ef5db690)

Navrhuju tady upravit několik názvů (soubor 480.scr):
**Skládání židle** -> **Skládací židle** (to je ta na letišti v salónku)
**Sklenice** -> **Sklo** (je to zvuk rozbíjejícího se skla)
**Nedotýkat se** -> **Prdnutí** (nevím, proč se to jmenuje takhle, koukal jsem i do angličtiny, kde je Do not touch, každopádně když se ta smyčka pustí, je to prd)

**Comment by miracleflame** [comment]
S tým "Nedotýkat se" to chápem ako úmyselný (Al Lowe) vtip, ale tiež si myslím, že to nikoho neurazí pomenovať po pravde.

**Comment by PetrCejpek** [comment]
Vtip, jakože "tohle tlačítko nemačkejte"? :-D
