### ISSUE TITLE
Na dotek je to přesně jako %s.

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#28]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/eeaef4a2-59a4-450b-be3c-6fe21f47e9ed)

Tady je trochu divný překlad, navíc je to něco jako "smartstring", kde se vkládá proměnná %s (v tomhle případě chlupaté kostky). Musí se to přeformulovat tak, aby ze slovesa/přísudku, pokud se použije, nebylo poznat jednotné a množné číslo a %s musí fungovat jako podmět (v prvním pádu). Tenhle problém bude u vícero vět v celé hře.

Návrh překladu v tomto případě:
**Jen %s, nic víc.**
(-> Jen chlupaté kostky, nic víc.)

**Comment by miracleflame** [comment]
Opravené v 1aea113267e2e6989b8ce7b29e84c337e9ef23fa v 0.tex
Na dotek je to přesně jako %s.
(originál This feels exactly like...)

**Comment by miracleflame** [comment]
doopravené v druhom súbore commitu 0c18bb7d27d7379baaf6820b92b55d91fee818ce
môže byť Na dotek je to přesně jako %s.
?

**Comment by PetrCejpek** [comment]
Mám pocit, že jsem na tuhle větu narazil i na Trampově promenádě, když jsem použil ikonu ruky na projíždějícího bruslaře. Tam mi ta formulace "na dotek..." nezní úplně dobře. Pokusím se to ještě zreplikovat.

**Comment by miracleflame** [comment]
Táto generická hláška sa zobrazí na všetko pod ikonou ruky, čo nemá svoju vlastnú hlášku, áno aj na postavách sa mi to stávalo.

**Comment by miracleflame** [comment]
Univerzálne by mohlo byť
%s je na dotek přesne jako bys čekal.

**Comment by PetrCejpek** [comment]
Já nevím, ale když budu sahat na lidi, moc mi tahle hláška nesedí. I když v originále to tak víceméně je, já bych to tak asi neřekl. 

Jinak jsem to otestoval, ve hře se to zobrazuje dle očekávání.

**Comment by miracleflame** [comment]
Asi nerozumiem, či sa tu odo mňa očaváva ďalšia akcia a aká...?

**Comment by PetrCejpek** [comment]
Jen jsem chtěl vlastně znát tvůj názor. :-) Asi to teda upravím sám dle vlastního uvážení (je to v tex souborech 0.tex a 160.tex).

**Comment by miracleflame** [comment]
Ja by som dal bez akéhokoľvek váhania
Na dotek je %s přesne jako bys čekal.

**Comment by PetrCejpek** [comment]
To je lepší tvoje první: **Na dotek je to přesně jako %s.**, protože v tom případě je přísudek _je_ a podmět _to_.
V případě: **Na dotek je %s přesně jako bys čekal.** je ale přísudek _je_ a podmět _%s_, což může být problém, když je %s v množném čísle (např. chlupaté kostky).

Já bych to trochu změnil například na: **Tohle ti připadá přesně jako %s.** Zbavíme se tak toho _dotyku_, který mi tam nesedí.

**Comment by miracleflame** [comment]
pravda
