### ISSUE TITLE
Lůzři

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#30]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/0e7424ee-4d1f-4ff2-af76-a118d2c85777)

Tady se očividně jedná o životopisy kandidátek, které nepostoupily do finále. Místo **Tahle zásuvka je nadepsaná "Lůzři".** přeložit jako **Tahle zásuvka je nadepsaná "Nepostupující".**

**Comment by miracleflame** [comment]
Noale v originále tam je "Losers" a nie Failed či niečo v tom zmysle. Je to forma humoru bez servítky. Si si istý, že to vyžaduje zmenu?

**Comment by PetrCejpek** [comment]
Ok, na tom něco bude. Nicméně neexistuje nějaké ekvivalentní slovo v ženském rodě? Každopádně, bude dobré přepsat alespoň ty **finalisty** na **finalistky**.

**Comment by miracleflame** [comment]
Lůzerky?
Fuchtle? :)

ChatGPT dal ešte takéto zaujímavé tipy
Nuly
Ztracené připady
Tragédky
Béčka

**Comment by PetrCejpek** [comment]
**Tragédky** asi nejlepší. :-)
