### ISSUE TITLE
Zrzavá/blonďatá dvojčata

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#31]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/cf6cb844-6132-4b8a-a1b6-8b185f645c1a)

Tady se opět vkládá proměnná %s. Je potřeba umazat **-vlasá** a barvy vlasů budou **zrzavá** a **blonďatá**.

**Comment by miracleflame** [comment]
Opravené v  6e56281056234b67d88edba26cdb056ccf978b54 v 180.sc a 180.tex
vo výsledku je tam zrzavá dvojčata... s blond variantou som sa zatiaľ nestretol, ale mala by byť blond dvojčata

**Comment by PetrCejpek** [comment]
Ok, takže to máme asi opravené?

**Comment by miracleflame** [comment]
jop
