### ISSUE TITLE
Výkon a nabíjení

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#35]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/42871ce4-b4d9-412c-98f0-7c977e03641c)

Jedná se o stav kamery a výdrž její baterie.
**Výkon:** -> **Zapnuto:**
**Nabíjení:** -> **Baterie:**

**Comment by miracleflame** [comment]
Opravené v 0e257abb9882bbcc0751826ce0882cea4421cc12 19.tex ako

Stav: %s

Výdrž baterie:
%d min %d sek

Takto to pôsobí lepšie podľa mňa, čo hovoríš?

**Comment by PetrCejpek** [comment]
> Opravené v [0e257ab](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/commit/0e257abb9882bbcc0751826ce0882cea4421cc12) 19.tex ako
> 
> Stav: %s
> 
> Výdrž baterie: %d min %d sek
> 
> Takto to pôsobí lepšie podľa mňa, čo hovoríš?

Jo, toto je lepší. :-)
