### ISSUE TITLE
Pozvánka do kasina

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#36]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/e66b3c37-6927-4a46-9f9f-c6ab365bf8da)

**Navštívit** -> **Navštivte**

**Comment by miracleflame** [comment]
Opravené v 4ea0176b6a225b981a59b9a499eb5e6103122150
