### ISSUE TITLE
Vykání/tykání

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#37]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/8808b4c2-385e-452b-b2e0-ae1742d9b00e)

Tady by se mělo tykat. Když jsem dělal korekturu, nakonec jsem to volil tak, aby "vypravěč" hráči tykal, ale v menu a podobných ovládacích věcech se vykalo.

**Jste před** -> **Jsi před**

**Comment by miracleflame** [comment]
Opravené v d536e5d72a18562dc3b22680ae9a6c2c5e527477
