### ISSUE TITLE
Komentář v limuzíně

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#40]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/39829c94-8c00-426a-87e6-eb3fe5da98bb)

**Prosím, nerušte řidiče! Dělá, co je v jeho silách!** -> **Prosím, neruš řidiče! Dělá, co může!** ("Vypravěč" tyká. Řidiče lze tady chápat jako povolání, takže by snad neměl vadit rod - každopádně jsem druhou větu radši přeformuloval.)

**Comment by miracleflame** [comment]
a9c4583f86741658f450b179409b87e34c3e84d1
Prosím, nerušte řidičku! Dělá, co je v jejích silách!
replika len pre Larryho s ženskou, vykanie doopravím...
