### ISSUE TITLE
Řidička v limuzíně

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#42]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/edc852bc-d1a0-4159-bf2e-0d497edc0307)

Místo **řekl bych** -> **řekla bych**. Opět by se mohlo jednat o rodový konflikt. Nicméně si myslím, že nepoužitelný telefon je pouze u Larryho, když jede na letiště.

Dál na to potom navazuje věta: **Jsem si jistý, že nemáte nárok na...** -> **Jsem si jistá**

**Comment by miracleflame** [comment]
Opravené v 1aea113267e2e6989b8ce7b29e84c337e9ef23fa
