### ISSUE TITLE
BIG-R'S CREDIT CARNIVAL

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#53]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/b4cd133d-e40d-47ee-a398-70cc7079eb5e)

Tady je to nějak zvláštně zarovnané. Navíc se neshoduje nadpis a ten název v textu (otázka je, jestli to nebylo už v originále).

Návrh nadpisu:
**BIG-R'S CREDIT CARNIVAL**

Návrh úpravy v textu:
**Zavolejte Rogeru H. do Big-R's Credit Carnival!**

**Comment by miracleflame** [comment]
Asi hodné testu

**Comment by miracleflame** [comment]
Lepšie
![obrázok](https://github.com/user-attachments/assets/497ddd8d-c3d8-4dc6-9e25-28fe8417e9d1)

**Comment by PetrCejpek** [comment]
Mám pocit, že jsem tam dneska ráno ještě doplňoval pomlčku (aby se to v tom textu nedělilo na konci řádku). Mělo by to být commitnuté, radši zkontroluj.

**Comment by miracleflame** [comment]
dobrý postreh... áno videl som, ale toto som pozrel bez tvojej úpravy, takže v pohode.
