### ISSUE TITLE
Přetékající text na automatu na letenky

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#54]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/0112878d-fdbc-4903-b5ac-c54c9e8591b0)

Tady to přetéká, takže se to musí zkrátit a nejspíš budeme muset použít metodu pokus-omyl.

Návrh překladu:
**Hele, blbečku. Jestli tu svou kartu necháš tady, zařídím, aby tvoje kufry letěly bez mezipřistání do Muncie v Indianě.**

**Comment by miracleflame** [comment]
Hmm, nejako mi ten font nepripadá rovnaký, aspoň medzery medzi riadkami, ale teda funguje to
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/4a56123c-3357-4b98-9591-d7826a2889ec)
