### ISSUE TITLE
Palubní lístek

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#62]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/4edb86ec-bf96-4c52-b39e-0e8c514317b3)

Tady se vkládá proměnná %s. Navrhuju dát místo **až** pomlčku:
**%s - %s**, sedadlo...

**Comment by miracleflame** [comment]
A čo tak radšej rovno normálne
z %s do %s
? :)

**Comment by PetrCejpek** [comment]
Tam by chybělo skloňování. Například z "z Los Angeles do New Yorku" by to udělalo "z Los Angeles do New York".

**Comment by miracleflame** [comment]
Opravil som aj formát dátumu. Hodné otestovania.

**Comment by miracleflame** [comment]
Otestované
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/a800971a-7ec3-4770-baaa-2aa93e6f1c04)

**Comment by miracleflame** [comment]
Tak som ten kód fixol, aby to fungovalo
![obrázok](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/19254203/6b9c8f57-d29e-48d8-9942-e8a90fd141b6)
