### ISSUE TITLE
Ženský rod

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#63]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/43824a5a-a034-41b9-841c-eceb614db459)

Tady to má být v ženském rodě (hraje se za Patti):
**Nebojíš se. Pár drsných situací jsi už zvládla. Koneckonců, vzpomeň si, čím vším sis prošla v "Sukničkáři Larrym 3"!**

**Comment by miracleflame** [comment]
Rod opravený v 1aea113267e2e6989b8ce7b29e84c337e9ef23fa súbor 410.tex
formuláciu doupravím..
