### ISSUE TITLE
Inspektor Desmond (jméno speakera)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#64]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/8f36b063-98a6-412d-b335-ffaf64449984)

**Inspektor Desmond** (jméno speakera)

**Comment by miracleflame** [comment]
Opravené v 1aea113267e2e6989b8ce7b29e84c337e9ef23fa
