### ISSUE TITLE
Ty (jméno speakera - Patti)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#65]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/69382741-7617-4f7f-9ebb-63b4189b1a78)

**Ty** (jméno speakera)

Navíc tu mám poznámku (nestihnul jsem udělat screenshot), že někde před touhle replikou je v textu překlep - dvě pomlčky za sebou.

**Comment by miracleflame** [comment]
415.tex
^Jsi zaskočená. Ale vzhledem k požadavkům -- kdo by se na tu práci hodil lépe než ty? Bylo by sladké se těm chlapům pomstít, nejen za to dnešní zesměšnění, ale i za všechny ty ostatní případy, kdy jsi obětovala svůj talent pro bandu nevděčníků.
