### ISSUE TITLE
Odkaz na hudebního interpreta

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#67]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/0fcf4bcb-a09a-4ef0-a75c-e74f0a6689f0)

M.J.Q. je Modern Jazz Quartet. Takže je otázka:
1) nechat?
2) dát tam celý název?
3) vyměnit to za nějakého známějšího interpreta?
4) udělat spíš odkaz na něco českého?
5) dát obecnější odkaz - např. **Koneckonců, oni jsou sotva nějaká filharmonie!**

Pak tu mám poznámku (nemám bohužel screenshot), že v téhle konverzaci je věta **Jak začneme?**, která by spíš měla být **Kdy začneme?** (za mně to dává trochu větší smysl)

**Comment by miracleflame** [comment]
Ja som ten typ, čo je vždy za čo najviac pôvodného obsahu, čiže za mňa ponechať ale s celým menom... písať skratky do dialógov mi prišlo vždy tak nejako dezimerzívne (vymyslel som nové slovo?).

+
415.tex
^"Tak jak začneme?"

**Comment by PetrCejpek** [comment]
Ok, v tom případě tedy možnost 2.
