### ISSUE TITLE
Velitel Magor (jméno speakera)

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#69]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/2205d933-da6b-4b0a-b445-923a57aa3459)

**Velitel Magor** (jméno speakera)

**Comment by miracleflame** [comment]
Opravené v 1aea113267e2e6989b8ce7b29e84c337e9ef23fa 430.sc
