### ISSUE TITLE
Agent(ka) 88

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#74]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/17be4e59-fc11-4e2c-87bb-c964ac12062b)

Možná lepší **agentka 88**? Ta původní byla taky žena.

**Comment by miracleflame** [comment]
+ Agentko, ehm

**Comment by PetrCejpek** [comment]
Jo, jenom pozor, tady v té replice je to dvakrát.
