### ISSUE TITLE
Název státu

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#77]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/1306b496-5a7e-4f13-b561-95bf5e6ba69f)

Tady je zkratka státu USA, tak otázka, jestli to rozepisovat a překládat:
**MD** -> **Maryland**

Obdobně:
**PA** -> **Pensylvánie**

**Comment by miracleflame** [comment]
Je to text na displeji DataPaku s adresou, ktorá sa v praxi píše tak ako je, nemenil by som.

**Comment by PetrCejpek** [comment]
Ok.
