### ISSUE TITLE
Pattiini nohy

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#78]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/ee32c7df-d6f5-465f-9aa4-f14467b4ace4)

Tohle bude na 99 % Patti-related -> **Vždycky jsi měla pocit, že**

**Comment by miracleflame** [comment]
Opravené niekde v [hromady oprav](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/commit/1aea113267e2e6989b8ce7b29e84c337e9ef23fa) https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/8 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/9 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/12 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/14 https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/issues/15
