### ISSUE TITLE
návrh na opravu prekladu 140.tex "Postava naší hostitelky..."

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#8]
"Postava naší moderátorky..."

**Comment by PetrCejpek** [comment]
> "Postava naší moderátorky..."

Takže navrhuješ hostitelku? Mně teda moderátorka přijde lepší, v češtině mi přijde, že se hostitel v tomhle smyslu moc nepoužívá. (i když už jsem to někde viděl)

**Comment by miracleflame** [comment]
Nie, bolo to naopak, takže toto považujem za uzavreté. :)
