### ISSUE TITLE
n-bitové mince

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#84]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/9f8ad7b2-3c7f-45f2-bb42-e01748efd399)

Jestli jsem to pochopil správně, tak by to měly spíš být 1-bitové hry, ne? Čili 0/1, ano/ne, panna/orel. Případně, by se to mohlo přeformulovat jako **Vždycky jsi byl fanoušek her s binární logikou!**

**Comment by miracleflame** [comment]
Škoda, že nevidno, čo to tam je za cifra. Skúsil som si to zreprodukovať z uloženej pozície a mám tam 4-bitových, čo nedáva zmysel a na obrázku to nevyzerá ako 4ka. Ide o premennú %d (síce nechápem, čo by sa na tom malo meniť), takže meniť to by bol prolbém. Tieto premenné sa po úpravách skriptov zvyknú rozhodiť, tak to možno preto tam mám niečo iné.

Išiel by som do tej binárnej logiky, aj keď chápem, kam sa v tej dobe mierilo týmto herným humorom.

**Comment by PetrCejpek** [comment]
Pardon, za ten kurzor, je tam dvojka. Jestli do toho leze ta proměnná, tak bych do toho asi nesahal. I když mi ten vtip teda nedává smysl.

**Comment by miracleflame** [comment]
2-bit nedáva zmysel, to bol niekto pseudosmart, ale nie je problém z toho textu vyhodiť %d a pretestovať, či sa niekde niečo neposunulo v číslach na letisku a letenke. To môžem pozrieť v rámci finálneho testu, čo si dám ešte raz poriadne full screen s Roland MT-32 zvukovkou.

**Comment by miracleflame** [comment]
Ja som vedel, že bude stáť za to opýtať sa na fóre. Dostal som takéto info:
You have a certain number of quarters, tracked by global 168 gQuarters. In American English parlance, a quarter is also known as two bits, as in the price of a shave and a haircut. Therefore, if you have one quarter in change, looking at the item says "2-bit game player". The number goes up accordingly, so if you have four quarters you're an 8-bit player. Unfortunately, you can't have four quarters as the number is only directly assigned 2, 1, or 0, not incremented.

**Comment by PetrCejpek** [comment]
Hm, to je zajímavé. Otázka teda je, jestli to tam nechávat takto, nebo jestli se tam pokoušet dát nějaký český vtip/reálie. (když je ten původní vtip vztažený na jazyk).

Třeba tam prostě dát něco jako: **Halíře dělají talíře.** :-D

**Comment by miracleflame** [comment]
Uvažoval som, či by sa tá premenná, čo sa odvíja od počtu mincí nedala použiť tak, aby bolo proste jasné, koľko telefonátov môže Larry uskutočniť. Kľudne bez pokusu o vtip len niečo na spôsob "Máš tak akorát n. Kam zavoláš?"

**Comment by PetrCejpek** [comment]
To by byla jedna varianta, nicméně to n by bylo v tom případě nutné podělit dvěma. Jestli to chápu správně, tak 1 čtvrťák = 1 hovor = ale 2 bity

**Comment by miracleflame** [comment]
Podarilo sa mi v kóde anulovať násobenie dvoma, takže by to šlo. Ešte mi napadla replika
Můžeš si %n-krát zahrát na automatech.

**Comment by PetrCejpek** [comment]
Pokud se ti povedlo anulovat násobení, můžeme použít něco jako: **Za tolik peněz si můžeš %dx někam zavolat.** Otázka je, jestli chceme hráči dávat tuhle "nápovědu".

**Comment by miracleflame** [comment]
Myslím, že je to fér... ak sa nemýlim, určité veci sa v tejto hre dajú urobiť do PONR, čo je samo o sebe hejzlovina a mať nápovedu, že treba dva hovory, môže zachrániť... zvlášť keď letisko s dvoma hovormi navštívia ako posledné a už sa nezamýšlajú nad takou možnosťou. (v tom prípade by im asi nenapadlo ani skúmať znovu mince, jedine zo zvedavosti, keby im to nápoveda predtým vnukla overovať)

**Comment by PetrCejpek** [comment]
Ok, v tom případě bych teda volil tu poslední možnost: **Za tolik peněz si můžeš %dx někam zavolat.** (nezapomenout na to dělení/násobení dvěma)

**Comment by miracleflame** [comment]
![obrázok](https://github.com/user-attachments/assets/d46ddc3c-8cbc-49bc-9c27-eb84aa2130b3)
![obrázok](https://github.com/user-attachments/assets/d2ca0fe5-df57-4d92-9c11-bd56fe0b9817)

Všimol som si, že sa nám nejakým spôsobom vypadla hlavička k predmetu Čtvrťák (touto zmenou to nie je) a ani po analýze commitov za posledné 3 týždne mi to hlava nebere, ale asi to nebude týmto súborom. Na druhú stranu je to fajn v prípade, že je tých mincí viac, tak sa to nevolá v jednotnom čísle. Každopádne nechávam otvorené

**Comment by PetrCejpek** [comment]
To je teda materiál... Člověk někde něco přepíše a rozbije mu to něco jiného úplně na jiném místě. :-D

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/584a7759-06ff-4510-80a3-dec88b43ec44)
Zajímavé, mně tam ten nadpis zůstal. (Scummvm)

**Comment by miracleflame** [comment]
Tak to je divné, lebo mám všetky scr zhodné s aktuálnym repozitárom. Tiež ScummVM.

**Comment by miracleflame** [comment]
Nepodarilo sa mi to zreplikovať, odhadujem, že to bolo zmenou skriptu za chodu hry.
