### ISSUE TITLE
DayTrotter

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#86]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/8db7371c-f67d-4be0-989b-6a6de85cf534)

Tohle je podle všeho nějaký **diář**. Navrhuju to asi tak i přeložit, na internetu jsem našel jenom to, že DayTrotter bylo nějaké nahrávací studio nebo hudební skupina.

Pak tu mám poznámku (bohužel nemám screenshot), když Larry bere ten diář ze sedadla limuzíny, že je problém s rodem:
**by chtěl, aby sis to vzala** -> **by chtěl, aby sis ho vzal**

**Comment by PetrCejpek** [comment]
Myslím, že #201 to vrátilo zpátky z **diáře** na **DayTrotter**. :-/

**Comment by miracleflame** [comment]
Ako píšem v #201 toto nikdy nebolo preložené
Fix v 8be20b65ae46508986e1454effa5b3beaf97c5e3

Diář sa rozlične skloňuje a všade možne, hlavne vo všetkých kombináciách použitia na predmety a sweet spoty... preto label test.

**Comment by PetrCejpek** [comment]
![image](https://github.com/user-attachments/assets/6a04b4d6-4329-4486-af56-349a0b1c530d)
Otestováno.
