### ISSUE TITLE
Sjednocení názvu kavárny na různých místech

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#89]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/e340632e-9fa0-4522-90bf-da9bdfb7ed00)

![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/f699445b-7f27-4f07-8257-432a29777f4e)

![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/351201ad-b79f-4d16-bd27-884b65fe5f5b)

Na různých místech je název kavárny v trochu odlišných variacích. Navrhuju sjednotit na **kavárna Hard Disk Café**.

**Comment by miracleflame** [comment]
Na test

**Comment by PetrCejpek** [comment]
Otestováno, zdá se v pořádku.
