### ISSUE TITLE
Návrh prekladu talkera Scooter z rm140

### ISSUE THREAD

**Issue by miracleflame** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#9]
Preložil by som Scootera
napr. Frajer alebo Borec

**Comment by miracleflame** [comment]
Preložené ako Frajer v commite vyššie

**Comment by PetrCejpek** [comment]
Frajer asi ok. Nejspíš to má být v kontrastu k těm přitakávačům (yesmanům/podkuřovačům).
