### ISSUE TITLE
Pseudofrancouzština

### ISSUE THREAD

**Issue by PetrCejpek** [miracleflame/Leisure-Suit-Larry-5-CZ-translation#95]
![image](https://github.com/miracleflame/Leisure-Suit-Larry-5-CZ-translation/assets/30171208/31d5322c-0d67-4278-98dc-6d4468d03c62)

Tohle má být nějaká pseudofrancouzština, musíme se podívat, co je v originálu (nejspíš [mesijé]).

**Comment by miracleflame** [comment]
510.tex
"Wee, wee, moisture!" he replies.

**Comment by miracleflame** [comment]
Možno by bolo dobré pofrancúžtiť všetky repliky vrchního v tomto súbore, lebo vôbec nie sú.

**Comment by PetrCejpek** [comment]
Zkusím se na to podívat.

**Comment by PetrCejpek** [comment]
No, díval jsem se do souboru a v ostatních replikách moc náznaků francouzštiny ani v originálu není. Prozatím bych tu repliku z tohohle issue přepsal na fonetickou výslovnost a sice: **"Ví, ví, mesijé!" odpoví.**
